### ISSUE TITLE
index.css

### ISSUE THREAD

**Issue by Quantium** [CodeNinjaMX/C-sar_PortafolioG2#1]
El archivo _index.css_ hay que meterlo en **assets/styles/index.css** para tener ordenado el código.

Y de preferencia cámbiale el nombre a main.css u otra cosa que no sea index, en algunas ocasiones esto puede ocasionar problemas con algunos servidores.

**Comment by caesarcca** [comment]
Listo, ya organice las carpetas.

**Comment by caesarcca** [comment]
Que hay Andrés, oye no logro hacer que mis div´s dentro de id="travel" y id="foto", respectivamente, queden alineados en la misma fila. Quiero que queden como la última línea pero no logro hacerlo. Podrías ayudarme
